# hyprland.conf

# Copia y pega esto directamente

$color = rgba(22,22,22,1.0)
$inner_color = rgba(22,22,22,1.0)
$outer_color = rgba(138,138,141,1.0)
$font_color = rgba(242,244,248,1.0)
$check_color = rgba(51,177,255,1.0)

general {
    col.active_border = rgb(8A8A8D)       # O el color que elijas
    col.inactive_border = rgb(363636)
    border_size = 3                       # Ya reducido a 3
    gaps_in = 5
    gaps_out = 5
}

group {
    col.border_active = rgba(8A8A8Dee)
    col.border_inactive = rgb(363636)
    
    groupbar {
        col.active = rgba(8A8A8D99)
        col.inactive = rgba(36363688)
        text_color = rgb(f2f4f8)
        text_color_inactive = rgba(be95ffee)
    }
}

decoration {
    rounding = 4
    rounding_power = 3
    
    shadow {
        enabled = true
        range = 16
        render_power = 8
        color = rgba(22,22,22, 1)
    }
}

decoration {
    rounding = 10  # <--- ESTE ES EL VALOR
}
