# hyprland.conf

# Copia y pega esto directamente

$color = rgba(22,22,22,1.0)
$inner_color = rgba(22,22,22,1.0)
$outer_color = rgba(138,138,141,1.0)
$font_color = rgba(242,244,248,1.0)
$check_color = rgba(51,177,255,1.0)

animations {
    enabled = yes

    # Softer curve (less acceleration)
    bezier = soft, 0.25, 0.8, 0.25, 1

    # Configure the borderangle animation
    # Syntax: animation = NAME, ON(1), SPEED, CURVE, STYLE

    animation = borderangle, 1, 50, linear, loop

    # Keep windows calm
    animation = windows,     1, 3, soft
    animation = windowsIn,   1, 3, soft
    animation = windowsOut,  1, 2, soft
    animation = windowsMove, 1, 2, soft

    animation = fade,        1, 2, soft
    animation = layers,      1, 2, soft

    # Workspace: subtle vertical slide + fade
    animation = workspaces,  1, 4, soft, slidevertfade
}

general {
    col.active_border = rgb(8A8A8D)       # O el color que elijas
    col.inactive_border = rgb(363636)
    border_size = 2                       # Ya reducido a 3
    gaps_in = 2
    gaps_out = 4
}

group {
    col.border_active = rgba(ffa500ff) rgba(0000ffff) 45deg  # <-- Borde Activo para cambiar
    col.border_inactive = rgb(363636)
    
    groupbar {
        col.active = rgba(8A8A8D99) # <-- Borde Activo para cambiar
        col.inactive = rgba(36363688)
        text_color = rgb(f2f4f8)
        text_color_inactive = rgba(be95ffee)
    }
}

decoration {

    # 1. Dimming Inactive Windows (The Focus Effect)
    dim_inactive = true
    dim_strength = 0.25      # 0.0 to 1.0 (0.2 - 0.3 is usually the sweet spot)

    # 2. Transparency & Blur (The "Glass" Effect)
    active_opacity = 1.0     # Active window is fully opaque
    inactive_opacity = 0.90  # Inactive windows become slightly transparent

    rounding = 4
    rounding_power = 3
    
    shadow {
        enabled = true
        range = 16
        render_power = 8
        color = rgba(22,22,22, 1)
    }
}

decoration {
    rounding = 12  # <--- ESTE ES EL VALOR
    shadow {
        enabled = false
        range = 15
        render_power = 5
        offset = 0 0
    }

}
blur {
    enabled = true
    size = 3          
    passes = 4
    contrast = 1.1
    brightness = 1.1
    vibrancy = 0.2    
    vibrancy_darkness = 0.2
    noise = 0.03      
    ignore_opacity = true
    new_optimizations = on
}
    active_opacity = 0.93
    inactive_opacity = 0.92
    fullscreen_opacity = 1.0 
}

# Regla de Capas en Hyprland (rules.conf)

layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0, match:namespace walker
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace vicinae
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace vicinae
