# ────────────────────────────────────────────────────────────
# Custom Theme for Ghostty
# Made by Omarchist
# ────────────────────────────────────────────────────────────

background = #121111
foreground = #dcfce7

cursor-color = #eaeaea
cursor-text = #121212

selection-background = #3e3e3e
selection-foreground = #eaeaea

# normal colors
palette = 0=#222222
palette = 1=#D35F5F
palette = 2=#4ade7f
palette = 3=#d4953b
palette = 4=#93c5fd
palette = 5=#a78bfa
palette = 6=#86efab
palette = 7=#b4b4b4

# bright colors
palette = 8=#6b6b6b
palette = 9=#df6969
palette = 10=#86efab
palette = 11=#dfb265
palette = 12=#bfdbfe
palette = 13=#c4b5fd
palette = 14=#bbf7d0
palette = 15=#dcfce7
