# ────────────────────────────────────────────────────────────
# Custom Theme for Kitty
# Made with Omarchist
# ────────────────────────────────────────────────────────────

## name: Custom Theme

foreground              #dcfce7
background              #121111
selection_foreground    #121212
selection_background    #3e3e3e

cursor                  #eaeaea
cursor_text_color       #121212

# URL underline color when hovering with mouse
url_color               #dcfce7

# Tab bar colors
active_tab_foreground   #dcfce7
active_tab_background   #121111
inactive_tab_foreground #dcfce7
inactive_tab_background #121111
tab_bar_background      #dcfce7

color0  #222222
color8  #6b6b6b
color1  #D35F5F
color9  #df6969
color2  #4ade7f
color10 #86efab
color3  #d4953b
color11 #dfb265
color4  #93c5fd
color12 #bfdbfe
color5  #a78bfa
color13 #c4b5fd
color6  #86efab
color14 #bbf7d0
color7  #b4b4b4
color15 #dcfce7
